common_config:
  log_path: /workspace/log/
  imgs_path: /config/data/coco/

inference_config:
  model_acc: 0
  onnx_path: /config/model/yolov5s.onnx
  engine_path: /config/model/yolov5s_fp32.trt
  predict_path: /config/model/predict.data
  offline_test:
    img_path: /config/data/coco/car.jpg
    save_img: /workspace/image

preprocessor_config:
  batch_size: 1
  src_img_width: 3840
  src_img_height: 2160
  src_img_channel: 3
  dst_img_width: 640
  dst_img_height: 640
  dst_img_channel: 3

predict_config:
  decode_type: 1
  branch_num: 1
  predict_dim: [[1, 25200, 85]]
  branchs_dim: [[1, 3, 80, 80],[1, 3, 40, 40],[1, 3, 20, 20]]
  max_objects: 0
  obj_threshold: 0.25
  nms_threshold: 0.5
